const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

function convertToBool(text, fault = 'true') {
    return text === fault ? true : false;
}

module.exports = {
    SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoib092VEIrSXE1U1FEbUhkWnF4MzVjR0NZQXBhOFdpbGU2WmN2MG5FNGJGST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiM3MvMmQ5L1N6Y0xTS3E0Nm9wbzlFVGpDTmhhRkpGZkgxb3hXQjc2UkpoND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIrSkNYcC8xYUE1NUlNbU0wUDJqd3c4dkU4cTFYWnNGd29lcEl0TjA4NjB3PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJVRnRQTVp5eU9LOFQ3UXZUSit5QmtTR1A3M0ZIaWdMU3RIaHVCa3grN3k0PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IndHUTUvQmFBbjBXbW84TWNuQ1JWZkhaNWtBYUYwckt6TUpsSEhtTXBvV1E9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ii84dDhaYWZERlVzanN5c2FjTXVITUoyRWsrWFZiTEdtNEt4YnRJNEdZRkk9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY0hxVFlUVHQ3Y0xCY2svQWlpU2Zrc0V6UUdBZjBONkdnRnBySm5VWTFYQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUlkc1lTVUc4Ykk3eTg5NU1YZEQxaTdwRUlqZkhUS1RlclduNjJJcTdVND0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InRoNkpLektmY1NCUnVMQ254bjBxNDdVVlNIT1dITVZKWmNTdUZ3YXo4SEhscDZkT1ZXNUtMbG11RHpFYmpZRm12TnZ4L1huVERXVDZqUC8zMEljSmhRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjIwLCJhZHZTZWNyZXRLZXkiOiIxcmZlc1l0SGZPNVdURGEwcjlFQWxldVVWaE9ackJaWk9wS2FaY0NqUVprPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJNYUd5dUdWNVFqMnFTOUt4WkFIX3F3IiwicGhvbmVJZCI6IjIwNThkMDNhLTFhMTctNDhlOC1hOWJiLWExMTY1ZTVhYWRkNCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI1cXdoSW1wbWx6ZlZzdnM1eWRjeHpPdmV6TG89In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTnk5UUNYazBseXJmd3J2VTVvRHJIbDVKa3dvPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IlM1WldaVEhHIiwibWUiOnsiaWQiOiIxODQ5Mjc4NTA5NTo4NEBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiLwnZCD8J2QhPCdkIzwnZCO8J2QjSDwnZCZ8J2QgPCdkJHwnZCA8J2QivCdkIgifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ05HZTQzc1EyTTcvdkFZWUFpQUFLQUE9IiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IlU0TGc5cWJDektEZ0xhMjBXdTkvWVhVZ3crWTAzWEVNelYzYndDVEhYMTA9IiwiYWNjb3VudFNpZ25hdHVyZSI6IkxJVFdGdzdkMTlCT001S2Ewa2NGcnFRaGFUQU8vYzJvSkJ1UDRuREFtZi9ybHU5aDg0VGFCcXROTVpqdjJzZG81YW1saEJ6dm5WYS9LUUZlQllVRURnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJySGhXdTlHYlJKUEZsWnNtQmRWMHRxTlVidXkvZXdFSy9jTk9iQkhUNmdrajV0MGFsdFVJeEpVY2xING9kUlRnbmx6ckJRU1dnUjZPaG9PZFpWY2Jpdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjE4NDkyNzg1MDk1Ojg0QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlZPQzRQYW13c3lnNEMydHRGcnZmMkYxSU1QbU5OMXhETTFkMjhBa3gxOWQifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3Mzg1MzI3MDgsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBR1A5In0=",
    CAPTION: process.env.CAPTION || "code by yessertech ",
    AUTO_READ_STATUS: process.env.AUTO_READ_STATUS || "true",
    AUTO_REPLY_STATUS: process.env.AUTO_REPLY_STATUS || "true",
    READ_MESSAGE: process.env.READ_MESSAGE || "true", // Added auto-read configuration
    MODE: process.env.MODE || "private",
    AUTO_VOICE: process.env.AUTO_VOICE || "true",
    AUTO_STICKER: process.env.AUTO_STICKER || "false",
    AUTO_REPLY: process.env.AUTO_REPLY || "false",
    ALIVE_IMG: process.env.ALIVE_IMG || "https://files.catbox.moe/3kdkf6.jpg",
    ALIVE_MSG: process.env.ALIVE_MSG || "HII DEAR IM ONLINE I'M YESSER-MD WHATSAPP BOT 👍🤠",
    ANTI_LINK: process.env.ANTI_LINK || "true",
    ANTI_BAD: process.env.ANTI_BAD || "true",
    PREFIX: process.env.PREFIX || "%",
    FAKE_RECORDING: process.env.FAKE_RECORDING || "true",
    FAKE_TYPING: process.env.FAKE_TYPING || "false",
    ALWAYS_ONLINE: process.env.ALWAYS_ONLINE || "true",
    CURRENT_STATUS: process.env.CURRENT_STATUS || "true",
    AUTO_REACT: process.env.AUTO_REACT || "true",
    HEART_REACT: process.env.HEART_REACT || "true",
    OWNER_REACT: process.env.OWNER_REACT || "true",
    BOT_NAME: process.env.BOT_NAME || "yessertech",
    STATUS_REPLY: process.env.STATUS_REPLY || "`✅ your status seen 👀`",
    OMDB_API_KEY: process.env.OMDB_API_KEY || "76cb7f39", // omdbapi.com
};
